package simulations;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;

import java.time.Duration;

public class ServiceRequestSimulation extends Simulation {

    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl("http://localhost:4200")
        .acceptHeader("application/json")
        .contentTypeHeader("application/json");

    // QA-04-01: list → pause 1s → submit → pause 1s → list; 10 users over 30s
    private final ScenarioBuilder submitAndList = scenario("submit-and-list")
        .exec(http("list-service-requests")
            .post("/api/queries/list-service-requests")
            .body(StringBody("{}"))
            .check(status().is(200)))
        .pause(Duration.ofSeconds(1))
        .exec(http("submit-service-request")
            .post("/api/commands/submit-service-request")
            .body(StringBody(
                "{\"title\":\"Load test request\",\"description\":\"Generated by performance test\"}"
            ))
            .check(status().is(201)))
        .pause(Duration.ofSeconds(1))
        .exec(http("list-service-requests-again")
            .post("/api/queries/list-service-requests")
            .body(StringBody("{}"))
            .check(status().is(200)));

    // QA-04-02: list → pause 1s → search; 20 users over 30s
    private final ScenarioBuilder browseAndSearch = scenario("browse-and-search")
        .exec(http("list-service-requests")
            .post("/api/queries/list-service-requests")
            .body(StringBody("{}"))
            .check(status().is(200)))
        .pause(Duration.ofSeconds(1))
        .exec(http("search-service-requests")
            .post("/api/queries/search-service-requests")
            .body(StringBody("{\"query\":\"load test\"}"))
            .check(status().is(200)));

    {
        setUp(
            submitAndList.injectOpen(rampUsers(10).during(Duration.ofSeconds(30))),
            browseAndSearch.injectOpen(rampUsers(20).during(Duration.ofSeconds(30)))
        )
        .protocols(httpProtocol)
        .assertions(
            global().responseTime().percentile3().lt(1000),
            global().responseTime().percentile4().lt(2000),
            global().successfulRequests().percent().gt(99.0)
        );
    }
}
